### ISSUE TITLE
Test background color picker

### ISSUE THREAD

**Issue by simurai** [braver/isotope-light-ui#1]
If you wanna test the color picker,

try to replace [this](https://github.com/braver/isotope-light-ui/blob/master/lib/isotope-light-ui.coffee#L42-L43) with

``` coffee
type: 'color'
default: '#d5dbdb'
```

and [this](https://github.com/braver/isotope-light-ui/blob/master/lib/config.coffee#L40) with

``` coffee
color = atom.config.get('isotope-light-ui.backgroundColor').toHexString()
```

**Comment by braver** [comment]
Yes, I have been watching the settings-view pull requests and already got that working in a branch. It works like a charm, instant feedback! The input doesn't align nicely though, it's indented for some reason. Anyway, I've got a branch where I'm working that out and solving all the 1.0 deprecations.

**Comment by simurai** [comment]
Nice. Yeah, there is too much padding. The whole cell has a padding and then the actual control has minus margin to pull it back to the left. Not sure the exact reason, I think it's based on Bootstrap. But the mix of px + em's don't work well with your rem's mixed in. Hopefully that can be simplified. I like the scaling up/down by just changing the font-size.

**Comment by braver** [comment]
I've had to rewrite some other dimensions to use rems as well, so I'm ok with that and will tweak the layout when I finish up that branch. 

Are all of Atom's base styles done in Bootstrap?

**Comment by simurai** [comment]
well, I think it should still be improved in core so that theme creators don't have to worry about it. Also, because if themes have to style every detail, it's hard to make changes later in core without breaking themes. Not all is based on Bootstrap, but I think mostly the settings part.

**Comment by braver** [comment]
Yes, breakage would be a concern, there's a lot to keep up with. The development speed of the core team is awesome. Although I would expect things to settle down a bit later. Anyway, thanks for the info.
