### ISSUE TITLE
Search directory hides last row of each file match

### ISSUE THREAD

**Issue by alarrosa14** [braver/isotope-light-ui#11]
In every file, if there are n matches, it shows n - 1 of them (in cases of just 1 match, the result is not being shown).

![image](https://user-images.githubusercontent.com/7881301/28585202-e6dee1f4-7145-11e7-8174-1061b64fa325.png)

**Comment by alarrosa14** [comment]
I ~~fixed~~ patched it by adding this to my stylesheets:

```
.list-tree li {
    overflow: initial;
}
```

**Comment by lexicalunit** [comment]
Thanks for the issue and fix! I took the chance to sync `isotope-light-ui` with `isotope-ui` as well. Check out release v2.3.0.
