### ISSUE TITLE
Project/root folder name in wrong position

### ISSUE THREAD

**Issue by smlombardi** [braver/isotope-light-ui#2]
See image.

Using .174 and Kuroir theme, roboto regular setting

![screen shot 2015-01-20 at 1 27 41 pm](https://cloud.githubusercontent.com/assets/835148/5823141/4e09560a-a0a8-11e4-87a7-e82587244929.png)

**Comment by braver** [comment]
Well that's odd. I can't reproduce that. The entire layout is wrong. I've noticed chromium sometimes caches stuff or won't completely update when you switch ui themes. What happens when you reload?

**Comment by smlombardi** [comment]
Same with View > Reload and with quit and relaunch.  Tried a few fonts and settings, no changes.  Tried the default atom light theme. No difference.

You realize Deprecation Cop flags several errors? What I was using One Light Theme I had to fix those:

![screen shot 2015-01-20 at 2 01 31 pm](https://cloud.githubusercontent.com/assets/835148/5823695/efe3b8d6-a0ac-11e4-906a-8a512416050f.png)

**Comment by braver** [comment]
Yeah, I know, working on that (got it prepared in a branch) and will probably release tonight or tomorrow. 

Do you get that alignment thing in other projects as well? Could there be a weird character in the filename or something? It's so weird that I can't repro that in both my development and test environment, and have been using the theme all day at work...

**Comment by braver** [comment]
I just pushed patches for isotope and isotope-light in which the layout change that caused your problem has been reverted. Should now also be fully compliant with deprecation-cop.

**Comment by smlombardi** [comment]
looks great now, thanks.
