### ISSUE TITLE
add option to use gutter styling from syntax theme

### ISSUE THREAD

**Issue by nylki** [braver/isotope-light-ui#3]
It would be nice to have a checkbox, wether ther gutter should be styled or not by the isotope-ui theme.

**Comment by braver** [comment]
There's this almost all the way at the bottom?
![screen shot 2015-01-21 at 18 29 27](https://cloud.githubusercontent.com/assets/2543659/5841205/7e242542-a19b-11e4-8647-850564ae5134.png)

**Comment by nylki** [comment]
Wow, how could I have not noticed it? my mind must have played tricks with me, I am sorry. 
I am now on a different computer (posted the issue from os x, now on linux), I think I remember seeing more option in OS X though, than in linux:
![bildschirmfoto von 2015-01-21 20 29 36](https://cloud.githubusercontent.com/assets/1710598/5843335/4597a06c-a1ac-11e4-857c-e18ff4ef3f35.png)

**Comment by braver** [comment]
No worries. What you're seeing in Linux are just your settings that are different that the default. If you don't have Isotope as your active theme, settings don't show up properly. Also, you may need to reload to be able to access settings. I've already put in [a bug report](https://github.com/atom/settings-view/issues/347), the recent api changes seem to have broken some stuff for themes.

**Comment by nylki** [comment]
@braver ah right! I just noticed that enabling the theme gives you all the options.
