### ISSUE TITLE
gutter style checkbox has no effect

### ISSUE THREAD

**Issue by nylki** [braver/isotope-light-ui#7]
In version 2.0 the gutter style checkbox doesn't seem to have any effect. the syntax themes style is used in both cases (using pen-paper-coffee). I did reload atom after each toggling.

**Comment by braver** [comment]
Yeah, I'm not actually using that anymore, the gutter shouldn't be styled by the isotope theme. Atom doesn't clean up any config that you set but that isn't used by the package anymore. So you might see some orphaned config options. You can go into your config file and remove this, it should then also disappear from the settings view.

![screen shot 2015-03-30 at 14 57 08](https://cloud.githubusercontent.com/assets/2543659/6896577/10f6c9b6-d6ed-11e4-818c-560f6f3d85e5.png)
